version: "3.8"

services:
  mysql-post-service:
    image: mysql:8.0
    container_name: mysql-post-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=postservice_db
    ports:
      - "3306:3306"
    volumes:
      - postservice_data:/var/lib/mysql

  mysql-review-service:
    image: mysql:8.0
    container_name: mysql-review-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=reviewservice_db
    ports:
      - "3307:3306"
    volumes:
      - reviewservice_data:/var/lib/mysql

  mysql-comment-service:
    image: mysql:8.0
    container_name: mysql-comment-container
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=commentservice_db
    ports:
      - "3308:3306"
    volumes:
      - commentservice_data:/var/lib/mysql

volumes:
  postservice_data:
  reviewservice_data:
  commentservice_data:
